; Script generated by the ChatGPT
; Replace 'YourApp.zip' and 'YourApp.exe' with your actual zip file and executable name

Name "SimpleInternetMonitor Installer"
OutFile "SimpleInternetMonitor-WindowsInstaller.exe"
InstallDir "$PROGRAMFILES\SimpleInternetMonitor"

Page components
Page directory
Page instfiles

Section "SimpleInternetMonitor" SecApp

    ; Set output path to the installation directory
    SetOutPath $INSTDIR

    ; Extract files from the zip archive
    DetailPrint "Extracting files..."
    SetOverwrite on
    File "SimpleInternetMonitor-Windows.zip"

    ; Add registry key to enable autostart
    WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Run" "YourApp" "$INSTDIR\YourApp.exe"

SectionEnd

Section "Start Menu Shortcut" SecShortcut

    ; Create start menu shortcut
    SetShellVarContext all
    CreateDirectory "$SMPROGRAMS\SimpleInternetMonitor"
    CreateShortcut "$SMPROGRAMS\SimpleInternetMonitor\SimpleInternetMonitor.lnk" "$INSTDIR\SimpleInternetMonitor.exe"

SectionEnd

Section "Uninstall"

    ; Remove autostart registry entry
    DeleteRegValue HKCU "Software\Microsoft\Windows\CurrentVersion\Run" "SimpleInternetMonitor"

    ; Remove files and directories
    Delete "$INSTDIR\SimpleInternetMonitor.exe"
    Delete "$INSTDIR\*.*"
    RMDir "$INSTDIR"

    ; Remove start menu shortcut
    Delete "$SMPROGRAMS\SimpleInternetMonitor\SimpleInternetMonitor.lnk"
    RMDir "$SMPROGRAMS\SimpleInternetMonitor"

SectionEnd