name: GraalVM SimpleInternetMonitor builds
on:
  push:
#    branches:
#      - main
  pull_request:
#    branches:
#      - main
jobs:
  ubuntu-build:
    name: Windows SimpleInternetMonitor on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      # Setup the GraalVM with liberica, to avoid executing UI triggers
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'liberica'
          java-package: 'jdk+fx'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          cache: 'maven'

      # Execute the build script
      - name: Build
        run: |
          chmod +x ./buildNative_from_Linux.sh
          ./buildNative_from_Linux.sh

      - name: Compress action step
        uses: a7ul/tar-action@v1.2.0
        id: compress
        with:
          command: c
          files: |
            ./target-native/
          outPath: SimpleInternetMonitor-Linux.tar.gz

      - name: Upload Java Executable file
        uses: actions/upload-artifact@v4
        with:
          name: SimpleInternetMonitor.jar
          path: target/SimpleInternetMonitor.jar

      - name: Upload debug output
        uses: actions/upload-artifact@v4
        with:
          name: SimpleInternetMonitor-Linux.tar.gz
          path: SimpleInternetMonitor-Linux.tar.gz

      - name: Upload Debug Executable
        uses: actions/upload-artifact@v4
        with:
          name: SimpleInternetMonitor.debug
          path: target-native/SimpleInternetMonitor-Ubuntu.debug

  windows-build:
    name: SimpleInternetMonitor on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
    steps:
      - uses: actions/checkout@v4
      # Setup the GraalVM with liberica, to avoid executing UI triggers
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'liberica'
          java-package: 'jdk+fx'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          cache: 'maven'

      # Execute the build script
      - name: Build
        run: |
          .\buildNative_from_Windows.ps1

      # Install MSVC after the original build, because it can cause problems with GraalVM specified Path executables
      # Install the Windows MSVC to get editbin for modifying the appliation to not open in a visual console
      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
          spectre: true
      # Setup NSIS installer builder
      - name: Install NSIS
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop update
          scoop bucket add extras
          scoop install nsis
      # Setup App and Installer
      - name: Setup App as Console and Build Installer
        run: |
          .\buildNative_from_Windows_Installer.ps1

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: SimpleInternetMonitor-Windows.zip
          path: .\SimpleInternetMonitor.zip

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: SimpleInternetMonitor-WindowsInstaller.exe
          path: target-native\SimpleInternetMonitor-WindowsInstaller.exe
  create-release:
    name: Create release
    needs: [windows-build, ubuntu-build]
    runs-on: ubuntu-latest
    steps:
      - name: Get release version from pom.xml
        id: ver
        run: echo "project_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.ver.outputs.project_version }}
          release_name: Release ${{ steps.ver.outputs.project_version }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false